server:
  port: 8008
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    
spring:    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insta?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: insta
    password: bitc5600
    
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
      
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      
  security:
    user:
      name: test
      password: 1234   
          oauth2:      client:        registration:          facebook:
           client-id: 320469892500773
           client-secret: cb2b601b648074a6cdbed9e78e3c3f94
           scope:            - email
            - public_profile

test:
  secret: 이원모

file:
  path: C:/src/SpringBoot-Study/insta/src/main/resources/upload/

